import type { DialogueSequence } from '../core/types';

export const OPENING_DIALOGUE: DialogueSequence = {
  id: 'dada_intro_conversation',
  title: 'A Question to Ajja',
  lines: [
    {
      id: 'line_1',
      speaker: 'Vinay',
      text: 'Hey, Ajja.',
      cameraFocus: 'child',
      cameraEvent: 'child_close',
      animation: 'curious',
      audioCue: 'child_curious',
      audioFile: '/assets/audio/kid voice/v1.mp3',
    },
    {
      id: 'line_2',
      speaker: 'Ajja',
      text: 'Hmm, Vinay.',
      cameraFocus: 'old_man',
      cameraEvent: 'old_man_close',
      animation: 'talk',
      audioCue: 'dada_warm',
      audioFile: '/assets/audio/grandpa voice/v1.mp3',
    },
    {
      id: 'line_3',
      speaker: 'Vinay',
      text: 'Why do we celebrate Ganesh Chaturthi every year?',
      cameraFocus: 'child',
      cameraEvent: 'child_close',
      animation: 'curious',
      audioCue: 'child_curious',
      audioFile: '/assets/audio/kid voice/v2.mp3',
    },
    {
      id: 'line_4',
      speaker: 'Ajja',
      text: 'Why do you think we do?',
      cameraFocus: 'old_man',
      cameraEvent: 'old_man_close',
      animation: 'talk',
      audioCue: 'dada_warm',
      audioFile: '/assets/audio/grandpa voice/v2.mp3',
    },
    {
      id: 'line_5',
      speaker: 'Vinay',
      text: 'Because Ganesha is the most powerful God?',
      cameraFocus: 'child',
      cameraEvent: 'child_close',
      animation: 'curious',
      audioCue: 'child_curious',
      audioFile: '/assets/audio/kid voice/v3.mp3',
    },
    {
      id: 'line_6',
      speaker: 'Ajja',
      text: 'Not quite, my boy.',
      cameraFocus: 'old_man',
      cameraEvent: 'old_man_close',
      animation: 'talk',
      audioCue: 'dada_warm',
      audioFile: '/assets/audio/grandpa voice/v3.mp3',
    },
    {
      id: 'line_7',
      speaker: 'Vinay',
      text: 'Then why, Ajja?',
      cameraFocus: 'child',
      cameraEvent: 'child_close',
      animation: 'curious',
      audioCue: 'child_curious',
      audioFile: '/assets/audio/kid voice/v4.mp3',
    },
    {
      id: 'line_8',
      speaker: 'Ajja',
      text: 'That is a very old story.',
      cameraFocus: 'old_man',
      cameraEvent: 'old_man_close',
      animation: 'talk',
      audioCue: 'dada_warm',
      audioFile: '/assets/audio/grandpa voice/v4.mp3',
    },
  ],
};

export const STORY_MODE_DIALOGUE: DialogueSequence = {
  id: 'story_mode_introduction',
  title: 'The Legend of Ganesha Begins',
  lines: [
    {
      id: 'story_line_1',
      speaker: 'Old Man',
      text: 'Listen closely, my child. This sacred legend begins high upon holy Mount Kailash...',
      cameraFocus: 'two_shot',
      cameraEvent: 'story_mode',
      animation: 'talk',
      audioCue: 'dada_warm',
      audioFile: undefined,
    },
    {
      id: 'story_line_2',
      speaker: 'Child',
      text: 'Mount Kailash? Where Lord Shiva and Goddess Parvati lived?',
      cameraFocus: 'child',
      cameraEvent: 'child_close',
      animation: 'curious',
      audioCue: 'child_curious',
      audioFile: undefined,
    },
    {
      id: 'story_line_3',
      speaker: 'Old Man',
      text: 'Yes, little one. One day while Mahadev was deep in meditation, Goddess Parvati created a miraculous young boy of her own...',
      cameraFocus: 'two_shot',
      cameraEvent: 'story_mode',
      animation: 'talk',
      audioCue: 'dada_warm',
      audioFile: undefined,
    },
  ],
};

export const RETURN_HOME_DIALOGUE: DialogueSequence = {
  id: 'return_home_conversation',
  title: 'The Lesson of Lord Ganesha',
  lines: [
    {
      id: 'return_1',
      speaker: 'Child',
      text: 'Dada... Lord Shiva realized his mistake and gave him the sacred elephant head! And blessed him to be the first worshipped!',
      cameraFocus: 'child',
      cameraEvent: 'child_close',
      animation: 'curious',
      audioCue: 'child_excited',
    },
    {
      id: 'return_2',
      speaker: 'Old Man',
      text: 'Yes, Vinay. And remember his name: Vighnaharta — the remover of obstacles. Whenever you face hardship, remember that devotion and wisdom find a way.',
      cameraFocus: 'old_man',
      cameraEvent: 'old_man_close',
      animation: 'talk',
      audioCue: 'dada_warm',
    },
    {
      id: 'return_3',
      speaker: 'Child',
      text: 'I will never forget, Dada! Every single year, I will celebrate Ganesh Chaturthi and build Bappa a beautiful home!',
      cameraFocus: 'two_shot',
      cameraEvent: 'two_shot',
      animation: 'nod',
      audioCue: 'child_excited',
    },
    {
      id: 'return_4',
      speaker: 'Old Man',
      text: 'Keep that promise, beta. Seasons change, years will fly by... but the love we carry for Bappa and each other will never fade.',
      cameraFocus: 'two_shot',
      cameraEvent: 'two_shot',
      animation: 'talk',
      audioCue: 'dada_warm',
    },
  ],
};
