import type { DialogueSequence } from '../core/types';

export const OPENING_DIALOGUE: DialogueSequence = {
  id: 'dada_intro_conversation',
  title: 'A Question to Dada',
  lines: [
    {
      id: 'line_1',
      speaker: 'Child',
      text: 'Dada, can I ask you something?',
      cameraFocus: 'two_shot',
      cameraEvent: 'two_shot',
      animation: 'curious',
      audioCue: 'child_curious',
      audioFile: undefined,
    },
    {
      id: 'line_2',
      speaker: 'Old Man',
      text: 'Of course, my child. What is on your mind?',
      cameraFocus: 'two_shot',
      cameraEvent: 'old_man_close',
      animation: 'talk',
      audioCue: 'dada_warm',
      audioFile: undefined,
    },
    {
      id: 'line_3',
      speaker: 'Child',
      text: 'Why do we celebrate Ganesh Chaturthi with so much devotion?',
      cameraFocus: 'two_shot',
      cameraEvent: 'child_close',
      animation: 'curious',
      audioCue: 'child_curious',
      audioFile: undefined,
    },
    {
      id: 'line_4',
      speaker: 'Old Man',
      text: 'Ah, that is a wondrous tale from ancient times. Would you like to hear it?',
      cameraFocus: 'two_shot',
      cameraEvent: 'old_man_close',
      animation: 'talk',
      audioCue: 'dada_warm',
      audioFile: undefined,
    },
    {
      id: 'line_5',
      speaker: 'Child',
      text: 'Yes! Please tell me the story!',
      cameraFocus: 'two_shot',
      cameraEvent: 'two_shot',
      animation: 'nod',
      audioCue: 'child_excited',
      audioFile: undefined,
    },
  ],
};

export const STORY_MODE_DIALOGUE: DialogueSequence = {
  id: 'story_mode_introduction',
  title: 'The Legend of Ganesha Begins',
  lines: [
    {
      id: 'story_line_1',
      speaker: 'Old Man',
      text: 'Listen closely, my child. This sacred legend begins high upon holy Mount Kailash...',
      cameraFocus: 'two_shot',
      cameraEvent: 'story_mode',
      animation: 'talk',
      audioCue: 'dada_warm',
      audioFile: undefined,
    },
    {
      id: 'story_line_2',
      speaker: 'Child',
      text: 'Mount Kailash? Where Lord Shiva and Goddess Parvati lived?',
      cameraFocus: 'child',
      cameraEvent: 'child_close',
      animation: 'curious',
      audioCue: 'child_curious',
      audioFile: undefined,
    },
    {
      id: 'story_line_3',
      speaker: 'Old Man',
      text: 'Yes, little one. One day while Mahadev was deep in meditation, Goddess Parvati created a miraculous young boy of her own...',
      cameraFocus: 'two_shot',
      cameraEvent: 'story_mode',
      animation: 'talk',
      audioCue: 'dada_warm',
      audioFile: undefined,
    },
  ],
};

export const RETURN_HOME_DIALOGUE: DialogueSequence = {
  id: 'return_home_conversation',
  title: 'The Lesson of Lord Ganesha',
  lines: [
    {
      id: 'return_1',
      speaker: 'Child',
      text: 'Dada... Lord Shiva realized his mistake and gave him the sacred elephant head! And blessed him to be the first worshipped!',
      cameraFocus: 'child',
      cameraEvent: 'child_close',
      animation: 'curious',
      audioCue: 'child_excited',
    },
    {
      id: 'return_2',
      speaker: 'Old Man',
      text: 'Yes, Vinay. And remember his name: Vighnaharta — the remover of obstacles. Whenever you face hardship, remember that devotion and wisdom find a way.',
      cameraFocus: 'old_man',
      cameraEvent: 'old_man_close',
      animation: 'talk',
      audioCue: 'dada_warm',
    },
    {
      id: 'return_3',
      speaker: 'Child',
      text: 'I will never forget, Dada! Every single year, I will celebrate Ganesh Chaturthi and build Bappa a beautiful home!',
      cameraFocus: 'two_shot',
      cameraEvent: 'two_shot',
      animation: 'nod',
      audioCue: 'child_excited',
    },
    {
      id: 'return_4',
      speaker: 'Old Man',
      text: 'Keep that promise, beta. Seasons change, years will fly by... but the love we carry for Bappa and each other will never fade.',
      cameraFocus: 'two_shot',
      cameraEvent: 'two_shot',
      animation: 'talk',
      audioCue: 'dada_warm',
    },
  ],
};
