/**
 * Game Registry — Central config store for all 10 arcade mini-games.
 */
import type { MiniGameConfig } from './ArcadeTypes';

export const GAME_REGISTRY: MiniGameConfig[] = [
  {
    id: 'modak-catch',
    number: 1,
    title: 'Modak Catch',
    subtitle: 'Catch the falling modaks before they hit the ground.',
    genre: 'Arcade',
    difficulty: 'Easy',
    icon: '🍡',
    colors: { primary: '#d97706', secondary: '#92400e', accent: '#fef08a' },
    instructions: 'Catch the sweetness. Miss nothing.',
    controls: '← A / D → or Mouse',
    timerSeconds: 60,
  },
  {
    id: 'mushak-dash',
    number: 2,
    title: 'Mushak Dash',
    subtitle: 'Run, dodge and collect your way through the festival.',
    genre: 'Runner',
    difficulty: 'Medium',
    icon: '🐭',
    colors: { primary: '#059669', secondary: '#065f46', accent: '#6ee7b7' },
    instructions: 'Run fast. Jump high. Collect everything.',
    controls: 'SPACE to jump · ↓ to duck',
  },
  {
    id: 'pandal-builder',
    number: 3,
    title: 'Pandaal Builder',
    subtitle: 'Build a beautiful pandal piece by piece.',
    genre: 'Puzzle',
    difficulty: 'Medium',
    icon: '🏗️',
    colors: { primary: '#b45309', secondary: '#78350f', accent: '#fbbf24' },
    instructions: 'Place each component in the right spot.',
    controls: 'Click to select · Click to place',
  },
  {
    id: 'rangoli-memory',
    number: 4,
    title: 'Rangoli Memory',
    subtitle: 'Remember the pattern. Recreate the design.',
    genre: 'Memory',
    difficulty: 'Medium',
    icon: '🎨',
    colors: { primary: '#dc2626', secondary: '#991b1b', accent: '#fca5a5' },
    instructions: 'Watch carefully. Then recreate.',
    controls: 'Click tiles to match the pattern',
    timerSeconds: 90,
  },
  {
    id: 'dhol-rhythm',
    number: 5,
    title: 'Dhol Rhythm',
    subtitle: 'Feel the beat. Build the combo.',
    genre: 'Rhythm',
    difficulty: 'Hard',
    icon: '🥁',
    colors: { primary: '#7c3aed', secondary: '#5b21b6', accent: '#c4b5fd' },
    instructions: 'Hit the notes in time with the beat.',
    controls: 'A · S · D · F',
  },
  {
    id: 'eco-murti',
    number: 6,
    title: 'Eco Murti Maker',
    subtitle: 'Create a beautiful eco-friendly murti.',
    genre: 'Creative',
    difficulty: 'Easy',
    icon: '🪷',
    colors: { primary: '#0d9488', secondary: '#134e4a', accent: '#5eead4' },
    instructions: 'Choose wisely. Build beautifully.',
    controls: 'Click to select materials',
  },
  {
    id: 'vinayaka-quiz',
    number: 7,
    title: 'Vinayaka Stories',
    subtitle: 'Test what you know about Ganesha.',
    genre: 'Quiz',
    difficulty: 'Medium',
    icon: '📜',
    colors: { primary: '#ca8a04', secondary: '#854d0e', accent: '#fde68a' },
    instructions: 'Answer wisely. Learn more.',
    controls: 'Click or press 1-4',
    timerSeconds: 15,
  },
  {
    id: 'visarjan',
    number: 8,
    title: 'Visarjan Journey',
    subtitle: 'Guide the celebration safely homeward.',
    genre: 'Navigation',
    difficulty: 'Medium',
    icon: '🌊',
    colors: { primary: '#2563eb', secondary: '#1e40af', accent: '#93c5fd' },
    instructions: 'Guide the procession safely.',
    controls: 'Arrow keys or WASD',
    timerSeconds: 120,
  },
  {
    id: 'puja-collector',
    number: 9,
    title: 'Puja Collector',
    subtitle: 'Gather everything needed before the puja begins.',
    genre: 'Collection',
    difficulty: 'Easy',
    icon: '🪔',
    colors: { primary: '#ea580c', secondary: '#9a3412', accent: '#fdba74' },
    instructions: 'Find every sacred item in time.',
    controls: 'Arrow keys or WASD to move',
    timerSeconds: 90,
  },
  {
    id: 'obstacle-path',
    number: 10,
    title: "Ganesha's Obstacle Path",
    subtitle: 'Run, jump and reach the finish.',
    genre: 'Platformer',
    difficulty: 'Hard',
    icon: '🏃',
    colors: { primary: '#e11d48', secondary: '#9f1239', accent: '#fda4af' },
    instructions: 'Overcome every obstacle.',
    controls: 'WASD to move · SPACE to jump',
  },
];

export function getGameConfig(id: string): MiniGameConfig | undefined {
  return GAME_REGISTRY.find((g) => g.id === id);
}
